### PR TITLE
Update from Weblate

### PR DESCRIPTION
**Pull request by weblate**

### CODE REVIEW

**Comment by NathanBnm** [comment]
Please wait the last translation to appear before merging 😉

**Comment by Wohlstand** [comment]
No problem :ok_hand: :fox_face:

**Comment by Wohlstand** [comment]
@NathanBnm, When you'll complete most of the work, please notify me here. Anyway, you still make any future corrects at any moment and they are will be sent to here separately :fox_face: :wink:

**Comment by NathanBnm** [comment]
@Wohlstand for the moment it's 100% translated and I have no changes to made for the moment. So you can merge this without problem 😉

**Comment by Wohlstand** [comment]
Great :fox_face:

**Pull request merged**
